image: docker:latest

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: registry.gitlab.com/ehyland/somepainter-cms

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build_somepainter_cms:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA ./cms
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:latest
