image: docker:git

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: registry.gitlab.com/ehyland/somepainter-cms

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:latest

deploy:
  stage: deploy
  only:
    - master
  environment:
    name: production
    url: https://cms.somepainter.com
  script:
    - docker pull $IMAGE_NAME:$CI_COMMIT_SHA
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $IMAGE_NAME:production
    - docker push $IMAGE_NAME:production
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - ssh -o StrictHostKeyChecking=no eamon@eamon.sh "sh ~/eamon.sh-server/scripts/remote/update.sh"
