version: '3.3'

volumes:
  db_data:

services:
  cms:
    image: registry.gitlab.com/ehyland/dockerfiles/silverstripe:latest
    ports:
      - 80:80
    volumes:
      - .:/site
    environment:
      SS_ENVIRONMENT_TYPE: dev
      SS_DATABASE_SERVER: db
      SS_DATABASE_NAME: somepainter-dev
      SS_DATABASE_USERNAME: root
      SS_DATABASE_PASSWORD: root
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}

  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
